export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGOUT_USER = 'LOGOUT_USER';

export const LOAD_LEAGUES_SUCCESS = 'LOAD_LEAGUES_SUCCESS';
export const LOAD_LEAGUES_FAILURE = 'LOAD_LEAGUES_FAILURE';
export const LOAD_LEAGUES_PENDING = 'LOAD_LEAGUES_PENDING';

export const LOAD_PLAYERS_SUCCESS = 'LOAD_PLAYERS_SUCCESS';
export const LOAD_PLAYERS_FAILURE = 'LOAD_PLAYERS_FAILURE';
export const LOAD_PLAYERS_PENDING = 'LOAD_PLAYERS_PENDING';

export const LOAD_ROSTER_SUCCESS = 'LOAD_ROSTER_SUCCESS';
export const LOAD_ROSTER_FAILURE = 'LOAD_ROSTER_FAILURE';
export const LOAD_ROSTER_PENDING = 'LOAD_ROSTER_PENDING';

export const LOAD_STANDINGS_SUCCESS = 'LOAD_STANDINGS_SUCCESS';
export const LOAD_STANDINGS_FAILURE = 'LOAD_STANDINGS_FAILURE';